### ISSUE TITLE
Credentials exposed

### ISSUE THREAD

**Issue by JonasDev17** [dgs4ops/blogify#4]
Your [Google API credentials](https://github.com/dgs4ops/blogify/blob/master/blogify-backend/gcp_keyfile.json) are exposed.

**Comment by LittleDavide** [comment]
The key files are limited to Firebase

**Comment by schnellert** [comment]
They only have authorisations for to read data  there. The 'old' keyfile before is deactivated and has been removed, but i unterstand your point.

**Comment by schnellert** [comment]
Keyfile is deactivated and is removed and completed with the pr:
https://github.com/dgs4ops/blogify/pull/5

Thank you.
